site_name: Kelas Utsman

theme:
  name: 'material'
  language: en
  feature:
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
  palette:
    - scheme: slate
      primary: light green
      accent: teal

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: /docs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2024 utsmannn (Muhammad Utsman)

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/utsmannn
      name: utsmannn on Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/utsmannn/
      name: utsmannn on Linkedin